### ISSUE TITLE
Support for Mixtral (MOE)

### ISSUE THREAD

**Issue by rlancemartin** [abetlen/llama-cpp-python#1000]
Mixtral is getting added to llama.cpp now - 
https://github.com/ggerganov/llama.cpp/pull/4406

Using weights [here](https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF/blob/main/mixtral-8x7b-v0.1.Q4_K_M.gguf) downloaded to `models/mixtral-8x7b`.

These steps work (Mac M2 32GB) in llama.cpp -
```
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
git checkout mixtral
make -j && ./main -m models/mixtral-8x7b/mixtral-8x7b-v0.1.Q4_K_M.gguf -p "Building a website can be done in 10 simple steps:\nStep 1:" -n 400 -e
```

Trying the same w/ `llama-cpp-python-0.2.22`:
```
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.llms import LlamaCpp

llm = LlamaCpp(
    model_path="/Users/rlm/Desktop/Code/llama.cpp/models/mixtral-8x7b/mixtral-8x7b-instruct-v0.1.Q2_K.gguf",
    n_gpu_layers=1,
    n_batch=512,
    n_ctx=2048,
    f16_kv=True,
    callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]),
    verbose=True,
)
```

Error:
```
error loading model: create_tensor: tensor 'blk.0.ffn_gate.weight' not found
```

**Comment by jcgeo9** [comment]
we are anxiously waiting for this update :)

**Comment by ahuang11** [comment]
I believe it works already; just need to point to the custom build before import.

Here's how I did it:
```bash
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
git checkout mixtral
make -j
make libllama.so
```

```python
import os

os.environ["LLAMA_CPP_LIB"] = "/Users/ahuang/repos/llama.cpp/libllama.so"

import panel as pn
from llama_cpp import Llama

pn.extension()


async def callback(contents: str, user: str, instance: pn.chat.ChatInterface):
    response = llm.create_completion(contents, stream=True)

    message = ""
    for chunk in response:
        message += chunk['choices'][0]['text']
        yield message


llm = Llama(
    model_path="./mixtral-8x7b-v0.1.Q4_K_M.gguf",
    n_gpu_layers=0,
)
chat_interface = pn.chat.ChatInterface(callback=callback, callback_user="Mixtral")
chat_interface.send(
    "Send a message to get a reply from Mixtral!", user="System", respond=False
)
chat_interface.servable()
```
<img width="1327" alt="image" src="https://github.com/abetlen/llama-cpp-python/assets/15331990/053b7946-2e8b-40cc-9151-714cb3de2fc9">

**Comment by brandonrobertz** [comment]
> I believe it works already; just need to point to the custom build with os.env before import.

Yeah it def works rn with the [mixtral](https://github.com/ggerganov/llama.cpp/tree/mixtral) branch. The way I got it to work was by going into `vendor/llama.cpp` and then checking out the mixtral branch. Then build as usual. Full sequence:

```
git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
cd llama-cpp-python/
cd vendor/llama.cpp/
git checkout mixtral
cd ../../
python3 -m pip install -e .
``

**Comment by rlancemartin** [comment]
> > I believe it works already; just need to point to the custom build with os.env before import.
> 
> Yeah it def works rn with the [mixtral](https://github.com/ggerganov/llama.cpp/tree/mixtral) branch. The way I got it to work was by going into `vendor/llama.cpp` and then checking out the mixtral branch. Then build as usual. Full sequence:
> 
> ```
> git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
> cd llama-cpp-python/
> cd vendor/llama.cpp/
> git checkout mixtral
> cd ../../
> python3 -m pip install -e .
> ```

When the [Mixtral PR](https://github.com/ggerganov/llama.cpp/pull/4406) merges to llama.cpp, will we need to cut a new release of `llama-cpp-python`? Or will it then "just work"?

**Comment by brandonrobertz** [comment]
> When the [Mixtral PR](https://github.com/ggerganov/llama.cpp/pull/4406) merges to llama.cpp, will we need to cut a new release of `llama-cpp-python`? Or will it then "just work"?

For pip install to just start working it looks like a new release will be required. From the [build and publish action it](https://github.com/abetlen/llama-cpp-python/blob/main/.github/workflows/publish.yaml) it looks like whatever the current submodule commit of llama.cpp (`vendor/llama.cpp`) is set to is what the release will contain, which makes sense. You wouldn't want every person who pip installs this lib to get whatever the latest version of llama.cpp is.

**Comment by jcgeo9** [comment]
> > I believe it works already; just need to point to the custom build with os.env before import.
> 
> Yeah it def works rn with the [mixtral](https://github.com/ggerganov/llama.cpp/tree/mixtral) branch. The way I got it to work was by going into `vendor/llama.cpp` and then checking out the mixtral branch. Then build as usual. Full sequence:
> 
> ```
> git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
> cd llama-cpp-python/
> cd vendor/llama.cpp/
> git checkout mixtral
> cd ../../
> python3 -m pip install -e .
> ```

Well I have tried this, but it only works for previous models. When I try to host Mixtral model using the following command, it looks like the model is loaded correctly but it returns empty response. When I follow the same procedure with Llama 2, I get a response. So I guess the mixtral models are not loaded correctly since I have tried both Q4 and Q5 versions?
`python server --model ../../mixtral-8x7b-v0.1.Q4_K_M.gguf --n_gpu_layers 100 --n_ctx 32768 --n_batch 512 --port 1214 --host localhost`

**Comment by paryska99** [comment]
The PR got merged. Hopefully we see llama-cpp-python updated soon.

**Comment by m-from-space** [comment]
> When I try to host Mixtral model using the following command, it looks like the model is loaded correctly but it returns empty response.

Do you maybe use a stop token like `stop=["\n"]` and it starts the response with a newline? The model works in my case, but I realized that it takes waaay longer to start generating if the prompt is not just a short question. That sucks, I hope this is just some kind of performance bug.

**Comment by DutchEllie** [comment]
The llama.cpp version has been officially merged into their master branch

**Comment by abetlen** [comment]
This should be published now with v0.2.23, let me know if there are any issues.

Cheers!

**Comment by yourbuddyconner** [comment]
@abetlen You dropped this, king --> 👑

**Comment by Soumadip-Saha** [comment]
I have installed the latest version of llama-cpp-python but still getting the `AssertionError` error when I try to load the model `TheBloke/Mixtral-8x7B-v0.1-GGUF mixtral-8x7b-v0.1.Q4_K_M.gguf`.

Here is the code that I have run:
```
!CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama-cpp-python
!pip install huggingface-hub
```

> Requirement already satisfied: llama-cpp-python in /usr/local/lib/python3.10/dist-packages (0.2.33)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from llama-cpp-python) (4.5.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from llama-cpp-python) (1.23.5)
Requirement already satisfied: diskcache>=5.6.1 in /usr/local/lib/python3.10/dist-packages (from llama-cpp-python) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.10/dist-packages (from llama-cpp-python) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.11.3->llama-cpp-python) (2.1.4)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (0.20.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (2023.11.17)

```
!huggingface-cli download TheBloke/Mixtral-8x7B-v0.1-GGUF mixtral-8x7b-v0.1.Q4_K_M.gguf --local-dir /content/Models --local-dir-use-symlinks False
```

> Consider using `hf_transfer` for faster downloads. This solution comes with some limitations. See https://huggingface.co/docs/huggingface_hub/hf_transfer for more details.
downloading https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF/resolve/main/mixtral-8x7b-v0.1.Q4_K_M.gguf to /root/.cache/huggingface/hub/tmpvlx9a6yq
mixtral-8x7b-v0.1.Q4_K_M.gguf: 100% 26.4G/26.4G [01:57<00:00, 225MB/s]
/content/Models/mixtral-8x7b-v0.1.Q4_K_M.gguf

```
from llama_cpp import Llama
llm = Llama(
  model_path="/content/Models/mixtral-8x7b-v0.1.Q4_K_M.gguf",  # Download the model file first
  n_ctx=2048,  # The max sequence length to use - note that longer sequence lengths require much more resources
  n_threads=8,            # The number of CPU threads to use, tailor to your system and the resulting performance
  n_gpu_layers=35         # The number of layers to offload to GPU, if you have GPU acceleration available
)
```

> AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> [<ipython-input-4-3deed290a181>](https://localhost:8080/#) in <cell line: 1>()
> ----> 1 llm = Llama(
>       2   model_path="/content/Models/mixtral-8x7b-v0.1.Q4_K_M.gguf",  # Download the model file first
>       3   n_ctx=2048,  # The max sequence length to use - note that longer sequence lengths require much more resources
>       4   n_threads=8,            # The number of CPU threads to use, tailor to your system and the resulting performance
>       5   n_gpu_layers=35         # The number of layers to offload to GPU, if you have GPU acceleration available
> 
> 2 frames
> [/usr/local/lib/python3.10/dist-packages/llama_cpp/_internals.py](https://localhost:8080/#) in n_vocab(self)
>      65 
>      66     def n_vocab(self) -> int:
> ---> 67         assert self.model is not None
>      68         return llama_cpp.llama_n_vocab(self.model)
>      69 
> 
> AssertionError:
> 

Can anyone help me with this issue please? I have followed all the steps mentioned but I think do I need to do anything like `os.environ["LLAMA_CPP_LIB"] = "/Users/ahuang/repos/llama.cpp/libllama.so"` to load the model? Appreciate the help since I am first time trying to use `llama-cpp-python`.

**Comment by Borecjeborec1** [comment]
You need to reinstall the package.

run: `pip install llama-cpp-python  --upgrade --force-reinstall --no-cache-dir` and wait a while.

Then it should work :D
