### ISSUE TITLE
Fix functionary v2 integration

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#1181]
Had to temporarily revert some of the changes introduced in the functionary v2 integratoin. The issue is that the hf tokenizer fails to detokenize single tokens correctly without the previous tokens and the changes required to support that in `_create_completion` broke some of the normal llama.cpp detokenization. Working on a fix though.

**Comment by rgbkrk** [comment]
One thing I noticed is that `--chat_format chatml-function-calling` works properly (on the OpenAI compatible endpoint) while `--chat_format functionary` spits out raw chatml `<|from|><|stop|> Just checking in. How can I assist you today?<|stop|> assistant:`.

**Comment by kahagerman** [comment]
> One thing I noticed is that `--chat_format chatml-function-calling` works properly (on the OpenAI compatible endpoint) while `--chat_format functionary` spits out raw chatml `<|from|><|stop|> Just checking in. How can I assist you today?<|stop|> assistant:`.

You should probably be using `--chat_format functionary-v2` (Check which version your model is tuned for.)

**Comment by kahagerman** [comment]
Just adding my 2¢ / some comments on functionary(-v2) when using the server...

1. Is it expected behaviour right now on latest that streaming output is broken and missing spaces?  (This seems to be what this issue would address?)

2. It seems to be necessary to specify `--hf_pretrained_model_name_or_path`, but I simply cannot figure out how to point this at a local file.
I either get
`Exception: Please provide a valid hf_tokenizer_path from https://huggingface.co/meetkai when initializing the Llama class` (which is extra confusing since the field doesn't match the cli argument)
or some variant of:
`OSError: Incorrect path_or_model_id: './models/functionary/tokenizer.json'. Please provide either the path to a local folder or the repo_id of a model on the Hub.` <br/>
Pointing at a the relevant remote functionary HF repo does appear to work.
(I'm not sure if this is related to this issue or not...)

Ideally the functionary-v2 type would be detected and `--hf_pretrained_model_name_or_path` would use a sane default (or even better, use the Llama HF Tokenizer?  [might not be possible](https://github.com/abetlen/llama-cpp-python/pull/1078#issuecomment-1920744998)?

**Comment by rgbkrk** [comment]
Ah! Great, thank you. I totally forgot about that namespace versioning in the big functionary v2 PR.

**Comment by jeffrey-fong** [comment]
@abetlen Previously in the functionary v2 integration, I've implemented offset_mapping in LlamaHFTokenizer's `detokenize` method where you can pass in the previous tokens and it will return the detokenized difference between `tokens` and `prev_tokens`. I guess it will be tricky to elegantly determine whether to use offset mapping or not in `_create_completion` based on the type of tokenizer class.

**Comment by abetlen** [comment]
@jeffrey-fong just re-enabled the prev_tokens, it now works correctly for both, thank you again for the work integrating this model!

**Comment by kahagerman** [comment]
Do we still need to specify a HF Tokenizer model (`--hf_pretrained_model_name_or_path`), or do you mean that the need for this is removed as well?

**Comment by sweetcard** [comment]
does stream mode work now?

**Comment by jeffrey-fong** [comment]
@kahagerman you will still need to provide the path to a HF Tokenizer. The details for how to initialize the Llama class is in the `Functionary v2` toggle [here](https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#function-calling).

@sweetcard streaming is not supported yet as of v0.2.50.

**Comment by kahagerman** [comment]
@jeffrey-fong Sorry, I simply cannot seem to figure out how to do this with a local HF Tokenizer.  (For my use case, I don't want to be reliant on having connectivity to HuggingFace.)

Is a local tokenizer "path" possible?

**Comment by abetlen** [comment]
> @jeffrey-fong Sorry, I simply cannot seem to figure out how to do this with a local HF Tokenizer. (For my use case, I don't want to be reliant on having connectivity to HuggingFace.)
> 
> Is using a local tokenizer possible?

Yes, you should be able to load a local huggingface autotokenizer and pass it to the llama class like so:

```python
from llama_cpp import Llama
from llama_cpp.llama_tokenizer import LlamaHFTokenizer

model = Llama(
   ...
   tokenizer=LlamaHFTokenizer.from_pretrained("/path/to/local")
)
```
