### ISSUE TITLE
GPU-accelerated docker container

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#143]

**Comment by gjmulder** [comment]
This works, but is more a dev env for confirming that CuBLAS is working. As per [this issue](https://github.com/ggerganov/llama.cpp/issues/1283) the problem was the size of the prompt I was passing.

[Dockerfile.txt](https://github.com/abetlen/llama-cpp-python/files/11376906/Dockerfile.txt)

**Comment by abetlen** [comment]
@gjmulder thanks!

**Comment by shengkaixuan** [comment]
> 

@gjmulder   what do you mean by saying "does generate load on my NVidia 1080Ti, as expected:" in this issue ?https://github.com/ggerganov/llama.cpp/issues/1283

**Comment by shengkaixuan** [comment]
> 
@gjmulder  by the way ,i tried the gpu dockerfile  ,it works ,great stuff thanks.

**Comment by gjmulder** [comment]
@shengkaixuan 

> what do you mean by saying "does generate load on my NVidia 1080Ti, as expected:" in this issue ?[ggerganov/llama.cpp#1283](https://github.com/ggerganov/llama.cpp/issues/1283)

"BLAS calls are only called when the tensors meet certain dimensions. In your case, you need to pass a prompt with length of 32 or more tokens to main to make it use BLAS. After it processes the prompt, it will continue text generation without BLAS since the overhead in this case is too big and there is no benefit"

**Comment by abetlen** [comment]
@gjmulder thanks for the dockerfile, I've added it to the root of the project `Dockerfile.cuda`, unfortunately I don't think I can provide a pre-built image through github actions.

**Comment by gjmulder** [comment]
Credit due to @jmtatsch
