### ISSUE TITLE
Precompiled wheels 

### ISSUE THREAD

**Issue by ParisNeo** [abetlen/llama-cpp-python#440]
Hi,

Is there a way to have multiple precompiled wheels for this library?
I use it on multiple platforms and it fails to install so often because of build errors

Best regards

**Comment by gaby** [comment]
@ParisNeo I don't think there's a way, llama-cpp optimizes the code during build-time based on your CPU.

**Comment by abetlen** [comment]
@ParisNeo there are pre-built wheels that I originally set up for the textgeneration-webui guys to simplify their installation for windows users, those are in the releases. The issue is that as @gaby points out, without compiling on the host system llama.cpp will be slow because there's no way to map wheels to the optimizations used in llama.cpp.

One solution we're working on right now is docker images that build on startup (with optional caching), does that work for you?

**Comment by gjmulder** [comment]
Related to #243

**Comment by gaby** [comment]
@abetlen Is this done?
