### ISSUE TITLE
cublas install error

### ISSUE THREAD

**Issue by TianhaoFu** [abetlen/llama-cpp-python#449]
when i install with cublas:

i came across:
Value ‘SM_30‘ is not defined for option ‘gpu-name‘

could you help me?

**Comment by gjmulder** [comment]
It is a CUDA issue. Are you using an old GTX900 series GPU by chance? If so, you need to use an older version of CUDA as the latest CUDA doesn't support such old hardware.

If not, and as requested in the issue template, please try and reproduce the problem with [llama.cpp](https://github.com/ggerganov/llama.cpp) to confirm that the build issue isn't specific to `llama-cpp-python`. Most build issues are due to misconfigured environments or `llama.cpp` build issues.
