### ISSUE TITLE
Insufficent memory pool on GPU

### ISSUE THREAD

**Issue by DenizK7** [abetlen/llama-cpp-python#546]
**ggml_new_tensor_impl: not enough space in the context's memory pool (needed 13340448, available 10485760)**
I get the above error when I use a word that is very common in documents.

**I tried to fix by adding**
`
import torch
`
`
device = torch.device("cuda:0")
`
`
memory_fraction = 1.0
torch.cuda.set_per_process_memory_fraction(memory_fraction, device=device)
`
Unfortunately nothing changed when i added this code
**current version of cuda**
11.8

My system requirements are sufficient
 **NVIDIA GeForce RTX 3080 Ti Laptop GPU, compute capability 8.6**

**Comment by jasoncaojingren** [comment]
I also got the same error when try to run Langchain which call the API server by LlamaCppPython. Any idea to fix it? I do believe I have enough resources on the machine: 128G RAM + 24G GPU RAM.

Error message:

Llama.generate: prefix-match hit
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 35007776, available 12582912)
./run4_stablebeluga-13b.ggmlv3.q8_0.sh: line 1:   432 Segmentation fault      python -m llama_cpp.server --verbose True --host 0.0.0.0 --port 8000 --n_gpu_layers 100 --n_ctx 4096 --n_batch 4096 --n_threads 16 --model /mnt/c/TechBuilder/HuggingFace.co/TheBloke/StableBeluga-13B-GGML/stablebeluga-13b.ggmlv3.q8_0.bin

**Comment by jasoncaojingren** [comment]
I found if set the  --n_batch 4096 to a small number, ex,  --n_batch 512, could avoid this problem.

**Comment by HansvanHespen** [comment]
Got the same problem here: "ggml_new_tensor_impl: not enough space in the context's memory pool (needed 45034832, available 10485760)" when launching a prompt of 2800 tokens on a model llama 7b chat q3K_M in python, althouh n_ctx = 4048, and 32 GB Ram. I'm not using any VRAM. My llama-cpp-python dates from 31 july 2023.

**Comment by HansvanHespen** [comment]
I really can't emphasize enough how important this is. It's being resolved in codestar model,as I understand, but not in Llama-cpp-python. I downloaded the llama.cpp directory directly, and copied over the new dll's, but now my software doesn't recognize the model anymore. 

I'm now limited to 500 tokens, and that is far from enough and from the reason why I developed a model myself. 

I'm really disappointed. Put in a few weeks of work to make it all work, langchain isn't helping by the way, so I rewrote big parts of langchain myself. And finally, it doesn't work because of some parameter ctx -> mem that I cannot change.

High regards,

Hans

**Comment by DenizK7** [comment]
@jasoncaojingren I realized that changing the batch size might be the solution, but it does create performance changes and it looks like I'll have to lower the batch size each time as the file size continues to grow. I don't have any information on how the batch size should be determined exactly. I just know what it does :( I don't know exactly how it affects optimum values ​​or low values.

**Comment by SkyTim-404** [comment]
I tried downgrade llama-cpp-python to 0.1.74 and it works.
